website:
  title: "Rhyan Goozh"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

